# Generated by Django 5.0.2 on 2024-03-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_like_like_id_like_id_alter_like_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_date',
            new_name='buy_date',
        ),
    ]
