# Generated by Django 5.0.2 on 2024-03-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_rename_like_date_like_buy_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='buy_date',
            new_name='like_date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
            preserve_default=False,
        ),
    ]
