# Generated by Django 5.0.2 on 2024-03-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
