# Generated by Django 5.0.2 on 2024-03-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
