# Generated by Django 5.0.2 on 2024-03-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_posts_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='posts',
            new_name='user',
        ),
    ]
