# Generated by Django 5.0.2 on 2024-03-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_like_dislike_like_dislike_permi_like_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='dislike_permi',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_permi',
        ),
    ]
