# Generated by Django 5.0.2 on 2024-03-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_remove_like_dislike_permi_remove_like_like_permi'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='dislike_permi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='like_permi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
