# Generated by Django 5.0.2 on 2024-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_like_dislike_permi_like_like_permi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/uploads/'),
        ),
    ]
