# Generated by Django 5.0.2 on 2024-03-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_alter_posts_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
