# Generated by Django 5.0.2 on 2024-03-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='user',
        ),
    ]
