# Generated by Django 5.0.2 on 2024-03-04 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccounts_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='like_history',
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='accounts/images/'),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
