# Generated by Django 5.0.2 on 2024-03-04 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccounts_like_history_useraccounts_image_and_more'),
        ('posts', '0003_remove_posts_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='like_history',
            field=models.ManyToManyField(to='posts.like'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
