# Generated by Django 5.0.2 on 2024-03-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccounts_like_history_alter_useraccounts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='image',
        ),
    ]
