# Generated by Django 5.0.2 on 2024-03-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_useraccounts_like_history'),
        ('posts', '0014_rename_like_date_like_buy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='like_history',
            field=models.ManyToManyField(to='posts.like'),
        ),
    ]
