# Generated by Django 5.0.2 on 2024-03-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccounts_like_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='like_history',
        ),
    ]
