# Generated by Django 5.0.2 on 2024-03-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_useraccounts_like_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='image',
            field=models.ImageField(default=1, upload_to='accounts/images/'),
            preserve_default=False,
        ),
    ]
