# Generated by Django 5.0.2 on 2024-03-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useraccounts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='meet_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
