# Generated by Django 5.0.2 on 2024-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useraccounts_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
