# Generated by Django 5.0.2 on 2024-03-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_useraccounts_city_useraccounts_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
