# Generated by Django 5.0.2 on 2024-03-05 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_useraccounts_username'),
        ('posts', '0026_remove_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
    ]
