# Generated by Django 5.0.2 on 2024-03-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useraccounts_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='posts',
        ),
    ]
