# Generated by Django 5.0.2 on 2024-03-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_useraccounts_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='username',
        ),
    ]
