# Generated by Django 5.0.2 on 2024-03-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_useraccounts_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccounts',
        ),
    ]
